Revert "Fix `TypeError: string "" is not a function`"
This reverts commit 65c5c8c987178221a427f04c77b7dbf0654a4440.

Signed-off-by: Shon Feder <shon@informal.systems>